<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Element</name>
   <tag></tag>
   <elementGuidId>0d999dcb-85b2-44fc-a0d6-45b4ee7df8f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.table-header.col-first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='for-removal']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Element&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4282592-11c1-4925-a9da-66675d29e22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-header col-first</value>
      <webElementGuid>2ba10395-cdb2-4309-9026-9d2edef8c904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Element</value>
      <webElementGuid>bc96c044-8cb1-4b8b-8c5f-0ee701e8ea9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;for-removal&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;table-header col-first&quot;]</value>
      <webElementGuid>db8d1f36-9718-40f0-9489-048cd0d8909b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='for-removal']/div[2]/div</value>
      <webElementGuid>359ee430-508c-4bad-9947-10a2ba2e84bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminally Deprecated Elements'])[1]/following::div[2]</value>
      <webElementGuid>c50a7472-3ab5-4636-961b-fd3080861f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Constructors'])[1]/following::div[4]</value>
      <webElementGuid>c484c4cc-9a71-4ee9-8238-40f04da0544f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::div[1]</value>
      <webElementGuid>1a0fe874-04ed-4e43-9f45-ea3e2656072e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.internal.Require.argument(String, File)'])[1]/preceding::div[2]</value>
      <webElementGuid>37c18245-e641-49f9-b4ab-32fd69f08b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Element']/parent::*</value>
      <webElementGuid>74bf9a16-824f-49c5-81d5-42a8aeb1190f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>f9113e2d-6719-4575-a722-7294e65cfee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Element' or . = 'Element')]</value>
      <webElementGuid>812a6dbb-68d4-4353-bb55-56116e604f40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
